version: "3.9"

services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app:cached
      - defi_db_data:/app/defi.db
    environment:
      NODE_ENV: production
    command: ./init-db.sh && npm start

volumes:
  defi_db_data:
